### ISSUE TITLE
How to load project depenedices.

### ISSUE THREAD

**Issue by Andrew112** [rahulsahay19/AMA#13]
Rahul, how are you! I wanted to know if you could give me some direction on how to load my project dependencies for the textbook project! I am having difficulties doing this and need some help. I am speaking about the Building Single page application using ASP Code and Angular textbook. I need to now which plugins would i need to load the missing project dependencies after i clone the sample project from GitHub into Visual Studio. Please reply! Andrew

**Comment by rahulsahay19** [comment]
Hi,

With this title, I am having couple of books. I guess, you are talking about the latest one which I have written with chander. If that's the one, can you paste the screenshot of the problem. Also, have you tried downloading the project from github as finished project is already there.

Thanks,
Rahul

**Comment by Andrew112** [comment]
Rahula, that correct. I am talking about the book you published with chandler.  I cloned the project from github to my visual studio but it does not compile. Andrew
[screenshot_.docx](https://github.com/rahulsahay19/AMA/files/2081860/screenshot_.docx)
