### ISSUE TITLE
angular web components

### ISSUE THREAD

**Issue by Sushanthm12** [rahulsahay19/AMA#16]
I read your article about how to create multiple angular elements. It was helpful. can you assist me in understanding how to use the created web components in another angular application directly like html element??

**Comment by rahulsahay19** [comment]
I have already explained in medium. You can read it from my blog as well https://myview.rahulnivi.net/running-multiple-angular-elements-page/ . Entire working piece is already explained. However, in angular 9, I have not tested this as it might be enabled by default by ivy. You may check angular release docs as well.
