### ISSUE TITLE
Design Pattern

### ISSUE THREAD

**Issue by sonikaupadhyay** [rahulsahay19/AMA#3]
Hi,

I would like to understand design pattern and how we can select design design pattern based on scenario.

Thanks & Regards,
Sonika Upadhyay

**Comment by rahulsahay19** [comment]
Hi,

Thanks for writing to me. Basically, design patterns come by experience. Once you understand pros and cons of one and other design patterns, then only you can understand its usage. Basically, in a nutshell design patterns are like pre-defined solutions for achieving similar kind of problems. Let's say MVC is a design pattern which is very famous these days. Unit of work, Repository Pattern are very popular design patterns, which are heavily used during data interactions. Now, these are industry standards which is most often used across industry. For a fresher, newcomer, these patterns are more than enough. Now, once you understand these and implementation of these, you can then generalize the problem statement and then apply any of the design patterns from the famous book Gang of Four. 

Recently, I have released one book, which is the implementation of tons of client/server technologies plus design pattern. You can get the glimpse of the same @ http://bit.ly/Rahul-SPA-Core. Thanks!
