### ISSUE TITLE
Couldn't find a compatible version of asp.net core code snippet 

### ISSUE THREAD

**Issue by AbhimanyuAryan** [rahulsahay19/AMA#5]
<img width="1011" alt="screen shot 2017-01-28 at 11 24 48 pm" src="https://cloud.githubusercontent.com/assets/8083613/22398581/548ae9e4-e5b1-11e6-8327-44265cffc5d2.png">

**Comment by rahulsahay19** [comment]
Fixed. Try now. Restart VS-Code and then try installing the same!
