### ISSUE TITLE
Entity framework

### ISSUE THREAD

**Issue by mitpancha** [rahulsahay19/AMA#6]
Hello Rahul,

Could you just tell , how much EF is important to use in .net core, does it affects processing speeds when we use large size of database.

Little bit advantage and disadvantages of EF

Thanks,
Mitesh

**Comment by rahulsahay19** [comment]
Hi,

Frankly speaking its a myth that using dbContext impacts DB performance. If its designed keeping all design and modeling constraints in mind then there is no impication. On top of that there has been many performance improvements done in EF. Every new release you can expect more robust features getting added to EF. Currently, EF is one of the fastest and best ORM model in place. On top of that, if you need to build scalable DB, I would suggest keep multiple DBContext like schema-wise. This way segregation, Isolation, maintainability, performance, scalability ......everything can be maintained. 

Thanks,
Rahul
