### ISSUE TITLE
how to learn asp.net identity?

### ISSUE THREAD

**Issue by farhadibehnam** [rahulsahay19/AMA#7]
Hi

I'm a novice programmer in asp.net MVC and I'm working on my project it's about a dentistry website.in part of my project I need to use identity for authorization and authentication. and also I've read [pro asp.net MVC 5 platform](https://www.amazon.com/Pro-ASP-NET-MVC-5-Platform/dp/1430265418) it was good but I still couldn't understand it very well. I can't create a registration and login form for my project.as well as I found your book about asp.net identity. do you think it can help me? I'm confused about identity.and also did you explain about roles in your book?
please help me how to learn identity very well?

Thanks so much.

**Comment by rahulsahay19** [comment]
Yeah that's there. However, its on the newer version side as in Identity. So, the examples which I have given here is based on asp.net core. Although, Identity piece will remain same as far as code setup is required. Hence, those working examples you can get from the book and then you can inject in your asp.net mvc application. Thanks!
